### ISSUE TITLE
End User guidance?

### ISSUE THREAD

**Issue by DavidOry** [VisionEval/VE-Installer#3]
Will the end user guidance end up on VisionEval.org? Or does it exist somewhere in the repository now? If so, where?  Is the idea that the content currently here (https://visioneval.jeremyraw.com/) will end up on VisionEval.org?

**Comment by jrawbits** [comment]
The content on https://visioneval.jeremyraw.com is [in the Installer Repository here](https://github.com/VisionEval/VE-Installer/tree/master/www).  Dan is working on creating a page for VisionEval.org that will provide (a better version of) the same information.  We expect to have it live within the next week or so.

**Comment by jrawbits** [comment]
I'll close this issue with an updated URL once the new end user instruction page is live.

**Comment by dflynn-volpe** [comment]
Initial guidance is on the new [download page here](http://visioneval.org/category/3download.html); let's discuss on Monday what we want to add to this.
