### ISSUE TITLE
Benefit v. Cost?

### ISSUE THREAD

**Issue by DavidOry** [VisionEval/VE-Installer#5]
For the end user, it seems that:

(1) Download this zip file;
(2) Run this R script. 

Is definitely easier than:

(1) Clone this repository;
(2) Run this R script. 

But we'll be paying a price in code maintenance (there's a lot of code here) commitment for this convenience. It may be useful to test these workflows to see if users find the first path significantly easier/more reliable. Also, in the near term, we should think about the cost of keeping this code running versus removing/refactoring the aspects of VisionEval that make the installation of libraries fragile/difficult in the first place. Thoughts?

**Comment by jrawbits** [comment]
Key thought:  This is not an "issue" but a matter (an important matter) for discussion in our product management forums.
